### ISSUE TITLE
What is the face used by the different levels of pairs

### ISSUE THREAD

**Issue by angrybakon** [capitaomorte/autopair#46]
I want to change the color of the different levels of pairs (4). But I cannot find the associated face.

**Comment by angrybakon** [comment]
Anyone ?

**Comment by capitaomorte** [comment]
First of all, sorry for not replying earlier, but I've been very busy. Autopair doesn't set a particular face for "different levels of pair". If you google for "rainbow-mode" you might have some luck with that, I think.

**Comment by angrybakon** [comment]
Mmh I'm not sure how rainbow-mode.el can help here. All it does is putting a colored background on color strings.

**Comment by capitaomorte** [comment]
btw https://github.com/Fanael/rainbow-delimiters is the right link for the xtension I meant
