### ISSUE TITLE
Autopair makes eldoc show-arguments slow

### ISSUE THREAD

**Issue by luismoneda** [capitaomorte/autopair#52]
Autopair seems to inhibit eldoc somehow. The arguments don't appear as soon as i type the "(". Sometimes i have to navigate to the outside and return to see the function arguments displayed by eldoc. Smartparens doesn't present this particular problem.

**Comment by joaotavora** [comment]
I apologize, but I think you will agree with me that without a more data, like measured times, the mode you are working on, the presence of other packages, emacs versions, etc, this report amounts to little more than an opinion.

Two suggestions:

1. Perhaps you can try `electric-pair-mode` in emacs 25 and tell me if the same happens to you.

2. Familiarize yourself with starting Emacs with the `-Q` flag and write down the steps that lead to your problem.

**Comment by lgmoneda** [comment]
I think the gif below is a more accurate description of the behavior: i need to go out of the parenthesis and sometimes even to return to the inside to see eldoc acting. I was with an impression that it was slow, but i think that's not the case, i've missed the pattern i just described. I can give you further information if needed.

Emacs version: 24.4.1
Mode: python-mode with anaconda-mode, anaconda-eldoc-mode and company-anaconda;

![alt text](
https://github.com/lgmoneda/dot-emacs/blob/master/gifs/autopair.gif?raw=true "Pair modes and eldoc in Python")

**Comment by joaotavora** [comment]
So if I gather correctly, `electric-pair-mode` works nicely, right? Use that instead, I recommend it over autopair... I'll look into the problem in the meantime, when I have time.
