### ISSUE TITLE
autopair-insert-opening is slow in polymode cell

### ISSUE THREAD

**Issue by matsievskiysv** [capitaomorte/autopair#55]
It takes seconds to execute `autopair-insert-opening` when editing jupyter notebook via [ein](https://github.com/millejoh/emacs-ipython-notebook). It's probably due to use of [ploymode](https://github.com/polymode/polymode).

---
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-09-22, modified by Debian
autopair 20160304.1237

**Comment by joaotavora** [comment]
Hi @seregaxvm. 

Autopair is completely obsolete.  It probably still works.  But in Emacs 26.3 you want to use `electric-pair-mode`.  It a better autopair that I wrote.
